channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - codacy-coverage
  - lammps >=2022.06.23
  - mpi4py =3.1.4
  - openmpi
  - numpy
  - distributed 
  - dask-jobqueue
  - pyzmq =25.1.0