channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - codacy-coverage
  - lammps =2023.03.28
  - openmpi
  - numpy =1.23.5
  - mpi4py =3.1.4
  - pympipool =0.6.2
  - ase =3.22.1
  - scipy =1.11.1