channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - codacy-coverage
  - lammps =2023.08.02
  - mpich
  - numpy =1.26.0
  - mpi4py =3.1.4
  - pympipool =0.7.1
  - ase =3.22.1
  - scipy =1.11.3
