channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - codacy-coverage
  - lammps >=2022.06.23
  - mpich
  - numpy
  - distributed
  - dask-jobqueue
  - cloudpickle =2.2.1
  - mpi4py =3.1.4
  - pympipool =0.4.2
  - pyzmq =25.1.0