channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - codacy-coverage
  - lammps =2023.03.28
  - mpich
  - numpy =1.24.3
  - mpi4py =3.1.4
  - pympipool =0.6.1
  - ase =3.22.1
  - scipy =1.11.1
