channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - codacy-coverage
  - lammps =2023.03.28
  - openmpi
  - numpy
  - distributed 
  - dask-jobqueue
  - cloudpickle =2.2.1
  - mpi4py =3.1.4
  - pympipool =0.5.0
  - pyzmq =25.1.0