name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: .ci_support/environment-openmpi.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 5
      run: |
        pip install versioneer[toml]==0.29
        pip install . --no-deps --no-build-isolation
        coverage run  --omit="pylammpsmpi/_version.py,tests/*" -m unittest discover tests
        coverage xml
    - name: Coveralls
      uses: coverallsapp/github-action@v2
