name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.11"
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        use-mamba: true
        environment-file: .ci_support/environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      run: |
        coverage run --omit pylammpsmpi/_version.py -m unittest discover tests
    - name: Coverage
      shell: bash -l {0}
      run: |
        coverage combine
        coveralls
        coverage xml
